/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsBase64ConverterRouteImport } from './routes/tools/base64-converter'
import { Route as ToolsBinaryConverterRouteImport } from './routes/tools/binary-converter'
import { Route as ToolsCaseConverterRouteImport } from './routes/tools/case-converter'
import { Route as ToolsColorConverterRouteImport } from './routes/tools/color-converter'
import { Route as ToolsCronExplainRouteImport } from './routes/tools/cron-explain'
import { Route as ToolsCsvToJsonRouteImport } from './routes/tools/csv-to-json'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsBase64ConverterRoute = ToolsBase64ConverterRouteImport.update({
  id: '/tools/base64-converter',
  path: '/tools/base64-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsBinaryConverterRoute = ToolsBinaryConverterRouteImport.update({
  id: '/tools/binary-converter',
  path: '/tools/binary-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsCaseConverterRoute = ToolsCaseConverterRouteImport.update({
  id: '/tools/case-converter',
  path: '/tools/case-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsColorConverterRoute = ToolsColorConverterRouteImport.update({
  id: '/tools/color-converter',
  path: '/tools/color-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsCronExplainRoute = ToolsCronExplainRouteImport.update({
  id: '/tools/cron-explain',
  path: '/tools/cron-explain',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsCsvToJsonRoute = ToolsCsvToJsonRouteImport.update({
  id: '/tools/csv-to-json',
  path: '/tools/csv-to-json',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tools/base64-converter': typeof ToolsBase64ConverterRoute
  '/tools/binary-converter': typeof ToolsBinaryConverterRoute
  '/tools/case-converter': typeof ToolsCaseConverterRoute
  '/tools/color-converter': typeof ToolsColorConverterRoute
  '/tools/cron-explain': typeof ToolsCronExplainRoute
  '/tools/csv-to-json': typeof ToolsCsvToJsonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tools/base64-converter': typeof ToolsBase64ConverterRoute
  '/tools/binary-converter': typeof ToolsBinaryConverterRoute
  '/tools/case-converter': typeof ToolsCaseConverterRoute
  '/tools/color-converter': typeof ToolsColorConverterRoute
  '/tools/cron-explain': typeof ToolsCronExplainRoute
  '/tools/csv-to-json': typeof ToolsCsvToJsonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tools/base64-converter': typeof ToolsBase64ConverterRoute
  '/tools/binary-converter': typeof ToolsBinaryConverterRoute
  '/tools/case-converter': typeof ToolsCaseConverterRoute
  '/tools/color-converter': typeof ToolsColorConverterRoute
  '/tools/cron-explain': typeof ToolsCronExplainRoute
  '/tools/csv-to-json': typeof ToolsCsvToJsonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/tools/base64-converter'
    | '/tools/binary-converter'
    | '/tools/case-converter'
    | '/tools/color-converter'
    | '/tools/cron-explain'
    | '/tools/csv-to-json'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/tools/base64-converter'
    | '/tools/binary-converter'
    | '/tools/case-converter'
    | '/tools/color-converter'
    | '/tools/cron-explain'
    | '/tools/csv-to-json'
  id:
    | '__root__'
    | '/'
    | '/tools/base64-converter'
    | '/tools/binary-converter'
    | '/tools/case-converter'
    | '/tools/color-converter'
    | '/tools/cron-explain'
    | '/tools/csv-to-json'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ToolsBase64ConverterRoute: typeof ToolsBase64ConverterRoute
  ToolsBinaryConverterRoute: typeof ToolsBinaryConverterRoute
  ToolsCaseConverterRoute: typeof ToolsCaseConverterRoute
  ToolsColorConverterRoute: typeof ToolsColorConverterRoute
  ToolsCronExplainRoute: typeof ToolsCronExplainRoute
  ToolsCsvToJsonRoute: typeof ToolsCsvToJsonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/base64-converter': {
      id: '/tools/base64-converter'
      path: '/tools/base64-converter'
      fullPath: '/tools/base64-converter'
      preLoaderRoute: typeof ToolsBase64ConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/binary-converter': {
      id: '/tools/binary-converter'
      path: '/tools/binary-converter'
      fullPath: '/tools/binary-converter'
      preLoaderRoute: typeof ToolsBinaryConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/case-converter': {
      id: '/tools/case-converter'
      path: '/tools/case-converter'
      fullPath: '/tools/case-converter'
      preLoaderRoute: typeof ToolsCaseConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/color-converter': {
      id: '/tools/color-converter'
      path: '/tools/color-converter'
      fullPath: '/tools/color-converter'
      preLoaderRoute: typeof ToolsColorConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/cron-explain': {
      id: '/tools/cron-explain'
      path: '/tools/cron-explain'
      fullPath: '/tools/cron-explain'
      preLoaderRoute: typeof ToolsCronExplainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/csv-to-json': {
      id: '/tools/csv-to-json'
      path: '/tools/csv-to-json'
      fullPath: '/tools/csv-to-json'
      preLoaderRoute: typeof ToolsCsvToJsonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ToolsBase64ConverterRoute: ToolsBase64ConverterRoute,
  ToolsBinaryConverterRoute: ToolsBinaryConverterRoute,
  ToolsCaseConverterRoute: ToolsCaseConverterRoute,
  ToolsColorConverterRoute: ToolsColorConverterRoute,
  ToolsCronExplainRoute: ToolsCronExplainRoute,
  ToolsCsvToJsonRoute: ToolsCsvToJsonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
