/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsBase64ConverterRouteImport } from './routes/tools/base64-converter'
import { Route as ToolsBinaryConverterRouteImport } from './routes/tools/binary-converter'
import { Route as ToolsCaseConverterRouteImport } from './routes/tools/case-converter'
import { Route as ToolsColorConverterRouteImport } from './routes/tools/color-converter'
import { Route as ToolsCronExplainRouteImport } from './routes/tools/cron-explain'
import { Route as ToolsCsvToJsonRouteImport } from './routes/tools/csv-to-json'
import { Route as ToolsHashGeneratorRouteImport } from './routes/tools/hash-generator'
import { Route as ToolsHexConverterRouteImport } from './routes/tools/hex-converter'
import { Route as ToolsHtmlEntitiesRouteImport } from './routes/tools/html-entities'
import { Route as ToolsImageCompressRouteImport } from './routes/tools/image-compress'
import { Route as ToolsImageCropperRouteImport } from './routes/tools/image-cropper'
import { Route as ToolsImageToBase64RouteImport } from './routes/tools/image-to-base64'
import { Route as ToolsJsonEscapeRouteImport } from './routes/tools/json-escape'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsBase64ConverterRoute = ToolsBase64ConverterRouteImport.update({
  id: '/tools/base64-converter',
  path: '/tools/base64-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsBinaryConverterRoute = ToolsBinaryConverterRouteImport.update({
  id: '/tools/binary-converter',
  path: '/tools/binary-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsCaseConverterRoute = ToolsCaseConverterRouteImport.update({
  id: '/tools/case-converter',
  path: '/tools/case-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsColorConverterRoute = ToolsColorConverterRouteImport.update({
  id: '/tools/color-converter',
  path: '/tools/color-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsCronExplainRoute = ToolsCronExplainRouteImport.update({
  id: '/tools/cron-explain',
  path: '/tools/cron-explain',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsCsvToJsonRoute = ToolsCsvToJsonRouteImport.update({
  id: '/tools/csv-to-json',
  path: '/tools/csv-to-json',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsHashGeneratorRoute = ToolsHashGeneratorRouteImport.update({
  id: '/tools/hash-generator',
  path: '/tools/hash-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsHexConverterRoute = ToolsHexConverterRouteImport.update({
  id: '/tools/hex-converter',
  path: '/tools/hex-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsHtmlEntitiesRoute = ToolsHtmlEntitiesRouteImport.update({
  id: '/tools/html-entities',
  path: '/tools/html-entities',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsImageCompressRoute = ToolsImageCompressRouteImport.update({
  id: '/tools/image-compress',
  path: '/tools/image-compress',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsImageCropperRoute = ToolsImageCropperRouteImport.update({
  id: '/tools/image-cropper',
  path: '/tools/image-cropper',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsImageToBase64Route = ToolsImageToBase64RouteImport.update({
  id: '/tools/image-to-base64',
  path: '/tools/image-to-base64',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsJsonEscapeRoute = ToolsJsonEscapeRouteImport.update({
  id: '/tools/json-escape',
  path: '/tools/json-escape',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tools/base64-converter': typeof ToolsBase64ConverterRoute
  '/tools/binary-converter': typeof ToolsBinaryConverterRoute
  '/tools/case-converter': typeof ToolsCaseConverterRoute
  '/tools/color-converter': typeof ToolsColorConverterRoute
  '/tools/cron-explain': typeof ToolsCronExplainRoute
  '/tools/csv-to-json': typeof ToolsCsvToJsonRoute
  '/tools/hash-generator': typeof ToolsHashGeneratorRoute
  '/tools/hex-converter': typeof ToolsHexConverterRoute
  '/tools/html-entities': typeof ToolsHtmlEntitiesRoute
  '/tools/image-compress': typeof ToolsImageCompressRoute
  '/tools/image-cropper': typeof ToolsImageCropperRoute
  '/tools/image-to-base64': typeof ToolsImageToBase64Route
  '/tools/json-escape': typeof ToolsJsonEscapeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tools/base64-converter': typeof ToolsBase64ConverterRoute
  '/tools/binary-converter': typeof ToolsBinaryConverterRoute
  '/tools/case-converter': typeof ToolsCaseConverterRoute
  '/tools/color-converter': typeof ToolsColorConverterRoute
  '/tools/cron-explain': typeof ToolsCronExplainRoute
  '/tools/csv-to-json': typeof ToolsCsvToJsonRoute
  '/tools/hash-generator': typeof ToolsHashGeneratorRoute
  '/tools/hex-converter': typeof ToolsHexConverterRoute
  '/tools/html-entities': typeof ToolsHtmlEntitiesRoute
  '/tools/image-compress': typeof ToolsImageCompressRoute
  '/tools/image-cropper': typeof ToolsImageCropperRoute
  '/tools/image-to-base64': typeof ToolsImageToBase64Route
  '/tools/json-escape': typeof ToolsJsonEscapeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tools/base64-converter': typeof ToolsBase64ConverterRoute
  '/tools/binary-converter': typeof ToolsBinaryConverterRoute
  '/tools/case-converter': typeof ToolsCaseConverterRoute
  '/tools/color-converter': typeof ToolsColorConverterRoute
  '/tools/cron-explain': typeof ToolsCronExplainRoute
  '/tools/csv-to-json': typeof ToolsCsvToJsonRoute
  '/tools/hash-generator': typeof ToolsHashGeneratorRoute
  '/tools/hex-converter': typeof ToolsHexConverterRoute
  '/tools/html-entities': typeof ToolsHtmlEntitiesRoute
  '/tools/image-compress': typeof ToolsImageCompressRoute
  '/tools/image-cropper': typeof ToolsImageCropperRoute
  '/tools/image-to-base64': typeof ToolsImageToBase64Route
  '/tools/json-escape': typeof ToolsJsonEscapeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/tools/base64-converter'
    | '/tools/binary-converter'
    | '/tools/case-converter'
    | '/tools/color-converter'
    | '/tools/cron-explain'
    | '/tools/csv-to-json'
    | '/tools/hash-generator'
    | '/tools/hex-converter'
    | '/tools/html-entities'
    | '/tools/image-compress'
    | '/tools/image-cropper'
    | '/tools/image-to-base64'
    | '/tools/json-escape'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/tools/base64-converter'
    | '/tools/binary-converter'
    | '/tools/case-converter'
    | '/tools/color-converter'
    | '/tools/cron-explain'
    | '/tools/csv-to-json'
    | '/tools/hash-generator'
    | '/tools/hex-converter'
    | '/tools/html-entities'
    | '/tools/image-compress'
    | '/tools/image-cropper'
    | '/tools/image-to-base64'
    | '/tools/json-escape'
  id:
    | '__root__'
    | '/'
    | '/tools/base64-converter'
    | '/tools/binary-converter'
    | '/tools/case-converter'
    | '/tools/color-converter'
    | '/tools/cron-explain'
    | '/tools/csv-to-json'
    | '/tools/hash-generator'
    | '/tools/hex-converter'
    | '/tools/html-entities'
    | '/tools/image-compress'
    | '/tools/image-cropper'
    | '/tools/image-to-base64'
    | '/tools/json-escape'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ToolsBase64ConverterRoute: typeof ToolsBase64ConverterRoute
  ToolsBinaryConverterRoute: typeof ToolsBinaryConverterRoute
  ToolsCaseConverterRoute: typeof ToolsCaseConverterRoute
  ToolsColorConverterRoute: typeof ToolsColorConverterRoute
  ToolsCronExplainRoute: typeof ToolsCronExplainRoute
  ToolsCsvToJsonRoute: typeof ToolsCsvToJsonRoute
  ToolsHashGeneratorRoute: typeof ToolsHashGeneratorRoute
  ToolsHexConverterRoute: typeof ToolsHexConverterRoute
  ToolsHtmlEntitiesRoute: typeof ToolsHtmlEntitiesRoute
  ToolsImageCompressRoute: typeof ToolsImageCompressRoute
  ToolsImageCropperRoute: typeof ToolsImageCropperRoute
  ToolsImageToBase64Route: typeof ToolsImageToBase64Route
  ToolsJsonEscapeRoute: typeof ToolsJsonEscapeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/base64-converter': {
      id: '/tools/base64-converter'
      path: '/tools/base64-converter'
      fullPath: '/tools/base64-converter'
      preLoaderRoute: typeof ToolsBase64ConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/binary-converter': {
      id: '/tools/binary-converter'
      path: '/tools/binary-converter'
      fullPath: '/tools/binary-converter'
      preLoaderRoute: typeof ToolsBinaryConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/case-converter': {
      id: '/tools/case-converter'
      path: '/tools/case-converter'
      fullPath: '/tools/case-converter'
      preLoaderRoute: typeof ToolsCaseConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/color-converter': {
      id: '/tools/color-converter'
      path: '/tools/color-converter'
      fullPath: '/tools/color-converter'
      preLoaderRoute: typeof ToolsColorConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/cron-explain': {
      id: '/tools/cron-explain'
      path: '/tools/cron-explain'
      fullPath: '/tools/cron-explain'
      preLoaderRoute: typeof ToolsCronExplainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/csv-to-json': {
      id: '/tools/csv-to-json'
      path: '/tools/csv-to-json'
      fullPath: '/tools/csv-to-json'
      preLoaderRoute: typeof ToolsCsvToJsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/hash-generator': {
      id: '/tools/hash-generator'
      path: '/tools/hash-generator'
      fullPath: '/tools/hash-generator'
      preLoaderRoute: typeof ToolsHashGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/hex-converter': {
      id: '/tools/hex-converter'
      path: '/tools/hex-converter'
      fullPath: '/tools/hex-converter'
      preLoaderRoute: typeof ToolsHexConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/html-entities': {
      id: '/tools/html-entities'
      path: '/tools/html-entities'
      fullPath: '/tools/html-entities'
      preLoaderRoute: typeof ToolsHtmlEntitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/image-compress': {
      id: '/tools/image-compress'
      path: '/tools/image-compress'
      fullPath: '/tools/image-compress'
      preLoaderRoute: typeof ToolsImageCompressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/image-cropper': {
      id: '/tools/image-cropper'
      path: '/tools/image-cropper'
      fullPath: '/tools/image-cropper'
      preLoaderRoute: typeof ToolsImageCropperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/image-to-base64': {
      id: '/tools/image-to-base64'
      path: '/tools/image-to-base64'
      fullPath: '/tools/image-to-base64'
      preLoaderRoute: typeof ToolsImageToBase64RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/json-escape': {
      id: '/tools/json-escape'
      path: '/tools/json-escape'
      fullPath: '/tools/json-escape'
      preLoaderRoute: typeof ToolsJsonEscapeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ToolsBase64ConverterRoute: ToolsBase64ConverterRoute,
  ToolsBinaryConverterRoute: ToolsBinaryConverterRoute,
  ToolsCaseConverterRoute: ToolsCaseConverterRoute,
  ToolsColorConverterRoute: ToolsColorConverterRoute,
  ToolsCronExplainRoute: ToolsCronExplainRoute,
  ToolsCsvToJsonRoute: ToolsCsvToJsonRoute,
  ToolsHashGeneratorRoute: ToolsHashGeneratorRoute,
  ToolsHexConverterRoute: ToolsHexConverterRoute,
  ToolsHtmlEntitiesRoute: ToolsHtmlEntitiesRoute,
  ToolsImageCompressRoute: ToolsImageCompressRoute,
  ToolsImageCropperRoute: ToolsImageCropperRoute,
  ToolsImageToBase64Route: ToolsImageToBase64Route,
  ToolsJsonEscapeRoute: ToolsJsonEscapeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
